# Generated by Django 5.2 on 2025-04-18 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='halloffame',
            name='url',
            field=models.URLField(),
        ),
    ]
