# Generated by Django 5.2 on 2025-04-18 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_alter_halloffame_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('grade', models.CharField(max_length=2)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
