# Generated by Django 5.2 on 2025-04-19 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0004_gradesummary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradesummary',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
